name: DockerPublish - Java

on:
  schedule:
    - cron: '24 21 * * *'
    
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker-push-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
          docker build ./softwares/java/17 --tag ghcr.io/funixg/funix-pteroq-eggs/java:17
          docker push ghcr.io/funixg/funix-pteroq-eggs/java:17

