name: DockerPublish - Java

on:
  schedule:
    - cron: '24 21 * * *'
    
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker-push-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push java 17
        run: |
          docker build ./softwares/java/17 --tag ghcr.io/funixg/java-pteroq:17
          docker push ghcr.io/funixg/java-pteroq:17

      - name: Build and push java 20
        run: |
          docker build ./softwares/java/20 --tag ghcr.io/funixg/java-pteroq:20
          docker push ghcr.io/funixg/java-pteroq:20

